config/routes.rb
Rails.application.routes.draw do
  root to:'todos#index'
  devise_for :users
  resources :todos do
    collection do
      get 'search'
      get 'searchh'
      get 'mytodo'
    end
    resources :comments, only: :create
  end
  resources :comments, only: :destroy
  resources :users,only: [:index,:show, :edit, :update]
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new
 
    if user.roll == 5
      can :read, :mng
    elsif user.roll == 1
      can :read, :ptn
    elsif user.roll == 2
      can :read, :ptnreader #Ptn主任
    elsif user.roll == 3
      can :read, :employee #社員
    elsif user.roll == 4
      can :read, :deputy #副店長
    elsif user.roll == 7
      can :manage,:all #admin
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'イベント' },
    { id: 3, name: '問題' },
    { id: 4, name: '提案' },
    { id: 5, name: 'やらなければいけないこと' },
  ]
  include ActiveHash::Associations
  has_many :todos
 end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :todo
  belongs_to :user
  has_one_attached :image

  validates :text,presence: true
end

app/models/roll.rb
class Roll < ActiveHash::Base
  self.data = [
    { id: 1, name: 'Ptn' },
    { id: 2, name: 'Ptn主任' },
    { id: 3, name: '社員' },
    { id: 4, name: '副店長' },
    { id: 5, name: '店長' },
    { id: 6, name: '退職' },
    { id: 7, name: '' },
  ]
  include ActiveHash::Associations
  has_many :todos
  has_many :users
 end

app/models/todo.rb
class Todo < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_one_attached :image
  belongs_to :urgency
  belongs_to :roll
  belongs_to :category
  has_many :comments

  with_options presence: true do
    validates :title
    validates :content
    with_options numericality: { other_than: 1 } do
      validates :category_id
    end
  end


  def self.search(search)
    if search != ""
      Todo.where('content collate utf8_unicode_ci LIKE(?)', "%#{search}%")
      .or(Todo.where('title collate utf8_unicode_ci LIKE(?)', "%#{search}%"))
      # collate utf8_unicode_ciは広範囲の検索を可能にする
    else
      Todo.none
    end
  end


end

app/models/urgency.rb
class Urgency < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '未着手' },
    { id: 3, name: '進行中' },
    { id: 4, name: '完了' },
    { id: 5, name: '中止' },
  ]
  include ActiveHash::Associations
  has_many :todos
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
  has_many :comments

  with_options presence: true do
  validates :name
  validates :birthday
  validates :phone, format: { with: /\A[0-9]{10,11}\z/ }
    with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/ } do
      validates :kana
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:kana,:phone,:birthday,:roll])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to todo_path(@comment.todo)
    else     
      @todo = @comment.todo
      @comments = @todo.comments
      render "todos/show"
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:text,:image).merge(user_id: current_user.id, todo_id: params[:todo_id])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  before_action :search_todo, only: [:index, :searchh]



  def index
    @todos = Todo.includes(:user).order('created_at DESC')
    # set_todo_column       # privateメソッド内で定義
    @roll1 = Todo.where(roll_id: 1 ).includes(:user).order('created_at DESC')
    @roll2 = Todo.where(roll_id: 1..2 ).includes(:user).order('created_at DESC')
    @roll3 = Todo.where(roll_id: 1..3 ).includes(:user).order('created_at DESC')
    @roll4 = Todo.where(roll_id: 1..4 ).includes(:user).order('created_at DESC')
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.create(todo_params)
    if @todo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @todo.comments.includes(:user)
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todo_path(@todo.id)
    else
      render :edit
    end
    # 更新成功→詳細画面偏移　更新失敗→編集画面偏移の処理
  end



  def destroy
    @todo.destroy
    redirect_to root_path
  end

  def search
    @todos = Todo.search(params[:keyword])
    @roll1 = Todo.where(roll_id: 1 ).search(params[:keyword])
    @roll2 = Todo.where(roll_id: 1..2 ).search(params[:keyword])
    @roll3 = Todo.where(roll_id: 1..3 ).search(params[:keyword])
    @roll4 = Todo.where(roll_id: 1..4 ).search(params[:keyword])

  end

  def searchh
    @searchh = @p.result.includes(:user)  # 検索条件にマッチした商品の情報を取得
    @searchh1 = @p.result.where(roll_id: 1 ).includes(:user)
    @searchh2 = @p.result.where(roll_id: 1..2 ).includes(:user)
    @searchh3 = @p.result.where(roll_id: 1..3 ).includes(:user)
    @searchh4 = @p.result.where(roll_id: 1..4 ).includes(:user)

  end

  def mytodo
    @mytodo = Todo.where(user_id: current_user.id).includes(:user).order("created_at DESC")
  end

  private

  def todo_params
    params.require(:todo).permit(
      :title,
      :content,
      :urgency_id,
      :roll_id,
      :image,
      :category_id,
      :start,
      :end
    )
          .merge(user_id: current_user.id)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @todo.user_id
  end

  def search_todo
    @p = Todo.ransack(params[:q])  # 検索オブジェクトを生成
  end

  # def set_todo_column
  #   @todo_title = Todo.select("title").distinct  # 重複なくnameカラムのデータを取り出す
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:edit, :update]



  def index
    @user = User.where(roll: 1..5 ).order(created_at: :desc)
    @retirement = User.where(roll: 6 ).order(updated_at: :desc)

  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to root_path  
    end
  end

end
private

  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.fetch(:user, {}).permit(:name,:roll,:password,:encrypted_password,:kana,:phone,:birthday,:email)
  end

  def move_to_index
    redirect_to action: :index unless current_user.roll == 5 || current_user.roll == 4 || current_user.roll == 7
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rcm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="<%= "https://www.googletagmanager.com/gtag/js?id=G-JJ788172G6" %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){
    dataLayer.push(arguments);
    }
  gtag('js', new Date());

  gtag('config', 'G-JJ788172G6');
</script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/todos/_todo.html.erb
<div class="row2">
  <div class="container3">
    <h3><%= link_to todo.title,todo_path(todo.id),method: :get%></h3>
    <div class="sabu">
      投稿者: <%= todo.user.name %>
    </div>
    <div class="sabu">
      カテゴリー: <%= todo.category.name %>
    </div>
    <div class="sabu">
      閲覧範囲: <%= todo.roll.name %>
    </div>
    <div class="sabu">
      <span class="ccccc">投稿日時: <%= l todo.created_at %></span>
    </div>
    <div class="sabu">
      <span class="ccccc">最終編集日時: <%= l todo.updated_at %></span>
    </div>
  </div>
</div>

app/views/todos/edit.html.erb
<div class="row6">
  <div class="container">
  <h2>こちらは編集画面です！</h2>
    <%= form_with model: @todo, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
          <div>
            <span class="sabu">必須</span>
          </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル" %>
      <div class="sabu">必須</div>
      <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"投稿内容" ,rows:"30" ,maxlength:"1000" %>
        <div class="sabu">閲覧範囲（Ptn＜Ptn主任＜社員＜副店長＜店長)<br>
                          ※プライベートな内容は閲覧範囲を変えて下さい。<br>
                          例：店長を指定すれば店長のみ閲覧出来ます。<br>
        </div>
      <%= f.collection_select(:roll_id, Roll.where(id: 1..5), :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="sabu">Ptn=店舗従業員全員閲覧可能です。</div>
        <br>

                <div >
              カテゴリー
              <span >選択必須</span>
            </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <br>
          <br>
          <h3>以下は必要であれば入力</h3>
          <hr class="hraaa">
          <div>画像添付</div>
          <%= f.file_field :image, id:"item-image" %>
            <span class="box10">開始日時：<%= f.date_field :start %></span>
                  <br>
            <span class="box10">終了日時<%= f.date_field :end %></span>
            <div class="weight-bold-text">
              現在の状況
            </div>
      <%= f.collection_select(:urgency_id, Urgency.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>


        <div class="sell-btn-contents">
          <%= f.submit "投稿する" ,class: :form__btn2 %>
        </div>
    <% end %>

    <%=link_to 'もどる', root_path, class:"modorubtn" %>
  </div>
</div>

app/views/todos/index.html.erb
  <h1 class="aaaaa">○○店　掲示板</h1><br>
  <div class="bbbbb">おはようございます！<%= current_user.name %>さん！</div>
      
    <div class="boxContainer">
      <div class="box9"><%= link_to "投稿する", new_todo_path %></div>
      <div class="box"><%= link_to "従業員リスト", users_path %></div>
      <div class="box"><%= link_to "自分の投稿", mytodo_todos_path %></div>
      <div class="box2"><%= link_to "ログアウト", destroy_user_session_path,method: :delete %></div>
    </div>
      <%= form_with(url: search_todos_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "タイトルと内容から検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
<div class="row7">
  <div class="container">
      <%= search_form_for @p, url: searchh_todos_path,class: "iiiii" do |f| %>
        <span class="showsabu">進行状況：</span><div class="box11"><%= f.collection_select :urgency_id_eq, Urgency.all, :id, :name,  include_blank: '指定なし' %></div>
        <span class="showsabu">カテゴリー：</span><div class="box11"><%= f.collection_select :category_id_eq, Category.all, :id, :name,  include_blank: '指定なし' %></div>
        <span class="showsabu">閲覧範囲：</span><div class="box11"><%= f.collection_select :roll_id_eq, Roll.where(id: 1..5), :id, :name,  include_blank: '指定なし' %></div>
        <br>
        <span class="showsabu">＜指定期間＞※設定してる投稿のみ</span>
        <div>
          <span class="box10"><%= f.date_field :start_gteq %></span>〜
          <span class="box10"><%= f.date_field :end_lteq_end_of_day %></span>
        </div>
        <%= f.submit '絞り込み検索',class: "search-btn2" %>
      <% end %>
  </div>
</div>


<div class="row2">
  <div class="container">
    <% if can? :read, :ptn %>
      <h2>投稿一覧</h2>
      <%= render partial: 'todo',collection: @roll1%>
    <% elsif can? :read, :ptnreader %>
      <h2>Ptn主任用投稿一覧</h2>
      <%= render partial: 'todo',collection: @roll2 %>
    <% elsif can? :read, :employee %>
      <h2>社員用投稿一覧</h2>
      <%= render partial: 'todo',collection: @roll3 %>
    <% elsif can? :read, :deputy %>
      <h2>副店長用投稿一覧</h2>
      <%= render partial: 'todo',collection: @roll4 %>
    <% elsif can? :read,:mng %>
      <h2>店長用全投稿一覧</h2>
      <%= render partial: 'todo',collection: @todos %>
    <% end %>
  </div>
</div>

app/views/todos/mytodo.html.erb
<div class="contents row2">
  <div class="container">
    <h2>自分の投稿一覧</h2>
    <%=link_to 'もどる', root_path, class:"modorubtn" %>
    <%= render partial: 'todo',collection: @mytodo %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="row6">
  <div class="container">
  <h2>なんでも投稿してください！</h2>
    <%= form_with model: @todo, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
          <div>
            <span class="sabu">必須</span>
          </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル" %>
      <div class="sabu">必須</div>
      <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"投稿内容" ,rows:"30" ,maxlength:"1000" %>
        <div class="sabu">閲覧範囲（Ptn＜Ptn主任＜社員＜副店長＜店長)<br>
                          ※プライベートな内容は閲覧範囲を変えて下さい。<br>
                          例：店長を指定すれば店長のみ閲覧出来ます。<br>
        </div>
      <%= f.collection_select(:roll_id, Roll.where(id: 1..5), :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="sabu">Ptn=店舗従業員全員閲覧可能です。</div>
        <br>



                <div >
              カテゴリー
              <span >選択必須</span>
            </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <br>
          <br>
          <h3>以下は必要であれば入力</h3>
          <hr class="hraaa">
          <div>画像添付</div>
          <%= f.file_field :image, id:"item-image" %>
            <span class="box10">開始日時：<%= f.date_field :start %></span>
                  <br>
            <span class="box10">終了日時<%= f.date_field :end %></span>
            <div class="weight-bold-text">
              現在の状況
            </div>
      <%= f.collection_select(:urgency_id, Urgency.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>


        <div class="sell-btn-contents">
          <%= f.submit "投稿する" ,class: :form__btn2 %>
        </div>
    <% end %>

    <%=link_to 'もどる', root_path ,class:"modorubtn"%>
  </div>
</div>

app/views/todos/search.html.erb
<%= form_with(url: search_todos_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
    <div class="contents row2">
      <div class="container">
        <% if can? :read, :ptn %>
          <h2>投稿一覧</h2>
          <%= render partial: 'todo',collection: @roll1%>
        <% elsif can? :read, :ptnreader %>
          <h2>Ptn主任用投稿一覧</h2>
          <%= render partial: 'todo',collection: @roll2 %>
        <% elsif can? :read, :employee %>
          <h2>社員用投稿一覧</h2>
          <%= render partial: 'todo',collection: @roll3 %>
        <% elsif can? :read, :deputy %>
          <h2>副店長用投稿一覧</h2>
          <%= render partial: 'todo',collection: @roll4 %>
        <% elsif can? :read,:mng %>
          <h2>店長用全投稿一覧</h2>
          <%= render partial: 'todo',collection: @todos %>
        <% end %>
        <div><%= link_to "検索条件を無くす", root_path,class:"modorubtn" %></div>
      </div>
    </div>
  </div>
</div>

app/views/todos/searchh.html.erb
<div class="contents row2">
  <div class="container">
    <h2>検索結果</h2>
    <%= link_to 'トップページへ戻る', root_path ,class:"modorubtn"%>
    <% if can? :read, :ptn %>
      <h2>投稿一覧</h2>
      <%= render partial: 'todo',collection: @searchh1%>
    <% elsif can? :read, :ptnreader %>
      <h2>Ptn主任用一覧</h2>
      <%= render partial: 'todo',collection: @searchh2 %>
    <% elsif can? :read, :employee %>
      <h2>社員用一覧</h2>
      <%= render partial: 'todo',collection: @searchh3 %>
    <% elsif can? :read, :deputy %>
      <h2>副店長用一覧</h2>
      <%= render partial: 'todo',collection: @searchh4 %>
    <% elsif can? :read,:mng %>
      <h2>店長用一覧</h2>
      <%= render partial: 'todo',collection: @searchh %>
    <% end %>
  </div>
</div>

app/views/todos/show.html.erb
<div class="row6">
  <div class="row4">
    <div class="container">
    <h2>投稿内容</h2>
      <h3><%= @todo.title %></h3>

      <div>
        <%= simple_format(@todo.content) %>
      </div>
    </div>
  </div>


  <%# 画像がある場合は表示する %>
  <% if @todo.image.present? %>
    <div class="row5">
      <div class="container4">
          <div class="box６">添付画像</div><br>
          <%=image_tag @todo.image ,class: 'sized' %>
      </div>
    </div>
  <% end %>
  <%# 画像がある場合は表示する %>
  <div class="boxContainer2">
    <span class="showsabu">投稿者：</span><div class="box3"><%= @todo.user.name %></div>
    <span class="showsabu">カテゴリー：</span><div class="box3"><%= @todo.category.name %></div>
    <span class="showsabu">進行状況：</span><div class="box3"><%= @todo.urgency.name %></div>
  </div>

  <div class="boxContainer2">
    <% if @todo.start.present? %>
      <span class="showsabu">開始日時：</span><div class="box3"><%= l @todo.start %></div>
    <% end %>
  </div>
    <div class="boxContainer2">
    <% if @todo.end.present? %>
      <span class="showsabu">開始日時：</span><div class="box3"><%= l @todo.end %></div>
    <% end %>
  </div>
    <div class="sabu">
      投稿日時: <%= l @todo.created_at %>
    </div>
    <div class="sabu">
      最終編集日時: <%= l @todo.updated_at %>
    </div>

      <%# ログイン・ログアウトの判定、ログアウト状態だと表示しない %>
      <% if user_signed_in?%> 
        <%# 投稿した本人が詳細ページを見た時の処理 %>
        <% if current_user.id == @todo.user_id %>
          <%= link_to "投稿内容編集", edit_todo_path(@todo.id), method: :get, class: "box4" %>
          <%= link_to "削除", todo_path(@todo.id),method: :delete, class:"box5" %>
        <% end %>
        <%# 投稿した本人が詳細ページを見た時の処理 %>
      <% end %>
      <%# ログイン・ログアウトの判定、ログアウト状態だと表示しない %>
  <div>
    <%= link_to "もどる", root_path,class:"modorubtn" %>
  </div>

<hr class="hrdef">
  <div class="row7">
    <div class="container5">
      <div class="input-birth-wrap">
          <%= form_with(model: [@todo, @comment], local: true) do |form| %>
            <%= form.text_area :text, placeholder: "投稿に対してコメントできます",rows:"1", class: :tiisaku2 %>
            <div class="ccccc">※必要であれば画像添付</div><%= form.file_field :image, class: :tiisaku %>
            <%= form.submit "コメントを投稿", class: :form__btn4 %>
          <% end %>
      </div>
      <div class="comments">
        <h4>＜コメント一覧＞</h4>
          <% @comments.each do |comment| %>
            <p>
              <%= link_to comment.user.name, "/users/#{comment.user_id}" %>：
              <%= comment.text %>
              <span class="ccccc"><%= l comment.created_at %></span>
            <% if current_user.id == comment.user_id %>
              <%= link_to "削除",comment_path(comment.id), method: :delete, class:"box5" %>
            <% end %>
            </p>
            <% if comment.image.present? %>
              <div >
                <%= image_tag comment.image,class: :sized%>
              </div>
            <% end %>
          <% end %>
    </div>
  </div>

  <div>
    <%= link_to "もどる", root_path,class:"modorubtn" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>プロフィール編集</h2>

    <%= form_with model: @user do |f| %>
      <div class="field">
      <label class="form-text">お名前</label><br />
        <%= f.text_area :name,size: "20x1", autocomplete: "name" %>
      </div>
      <div class="field">
        よみがな（カナ）<br />
        <%= f.text_area :kana,size: "20x1", autocomplete: "kana" %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>※<%= @minimum_password_length %> 文字以上入れて下さい。</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
      </div>

      <div class="field">
        電話番号<br />
        <%= f.text_area :phone,size: "20x1", autocomplete: "phone" %>
      </div>
      <div class="seinengappi" >生年月日を入力して下さい</div>
        <div class="input-birth-wrap">
          <%= raw sprintf(
                      f.date_select(
                        :birthday,
                        class:'select-birth',
                        id:"birth-date",
                        use_month_numbers: true,
                        prompt:'--',
                        start_year: 1930,
                        end_year: (Time.now.year - 5),
                        date_separator: '%s'),
                      "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      <div class="field">
        役職入力　※新しく入社の方はPtnを選択して下さい<br />
      <%= f.collection_select(:roll, Roll.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div><%= f.submit "プロフィールを編集する" ,class: :form__btn %></div>
    <% end %>
    <%=link_to 'トップへもどる', root_path,class:"modorubtn" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row2">
  <div class="container">
  <h2>従業員リスト(入社日降順)</h2>
    <%=link_to 'もどる', root_path,class:"modorubtn" %>
    <% @user.each do |t| %>
        <div class="container3">
          <%= link_to t.name,user_path(t.id),method: :get%>
          <div class="sabu">連絡先：<%= t.phone%></div>
          <div class="sabu">入社日：<%= t.created_at.strftime('%Y年%m月%d日')%></div>
        </div>
    <% end %>
  </div>
</div>

<div class="row2">
  <div class="container">
  <h2>退職者リスト</h2>
    <% @retirement.each do |t| %>
        <div class="container3">
          <%= link_to t.name,user_path(t.id),method: :get%>
          <div class="sabu">連絡先：<%= t.phone%></div>
          <div class="sabu">退職日：<%= t.updated_at.strftime('%Y年%m月%d日')%></div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row2">
  <div class="container">
    <h2><%= @user.name %>のユーザーページ</h2>
      <div>名前：<%= @user.name %></div>
      <div>よみがな（カナ）：<%= @user.kana %></div>
      <div>登録メール：<%= @user.email %></div>
      <div>電話番号：<%= @user.phone %></div>
      <div>誕生日：<%= @user.birthday.strftime('%m月%d日') %></div>
      <div>役職No：<%= @user.roll %></div>
      <div>入社日：<%= @user.created_at.strftime('%Y年%m月%d日')%><div>

        <% if can? :read, :deputy %>
          <div><%= link_to "プロフィール編集", edit_user_path(@user),class:"box4" %></div>
        <% end %>

        <% if can? :read,:mng %>
          <div><%= link_to "プロフィール編集", edit_user_path(@user),class:"box4" %></div>
        <% end %>
<br>
    <div><%=link_to 'トップへもどる', root_path,class:"modorubtn" %></div>
  </div>
</div>